### PR TITLE
Add license files

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by irwink** [comment]
The product name in the license files you provided do not match the actual product.  I have created a French licence file (the English one already exists at https://github.com/wet-boew/wet-boew-wpss/blob/master/Validator_GUI/License.txt ) to be added in the next product release.

**Comment by jpmckinney** [comment]
@irwink Where is the commit where you added the French file? I don't see it.

**Comment by LaurentGoderre** [comment]
License files should also be at the root of the repo so user don't have to search for them

**Comment by irwink** [comment]
File are committed to my local repository, they will be transferred to github as part of the next release.

**Pull request closed without merging**
